# Site settings
title: DSI - Data Science and Informatics
email: dsiufl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Data Science and Informatics Student Organization at the
    University of Florida (UF) connects students.
baseurl: "/www.dsiufl.org/" # the subpath of your site, e.g. /blog/
url: "http://www.dsiufl.org" # the base hostname & protocol for your site
twitter_username: dsiufl
github_username:  dsiufl

# Build settings
markdown: kramdown
